<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NEUNetworkAutoLogin</AssemblyName>
    <RootNamespace>NEUNetworkAutoLogin</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\AppIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\bin\portal-sso-login.js">
      <Link>Resources\portal-sso-login.js</Link>
      <LogicalName>NEUNetworkAutoLogin.Resources.portal-sso-login.js</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
